import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const toolRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(toolRoot, 'gui', 'index.html'), 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];

test('GUI script parses', () => {
  assert.doesNotThrow(() => new Function(script));
});

// Pull the two pure functions out of the page so their OUTPUT can be asserted, not just
// their syntax. A parse-only check previously let a broken highlighter ship.
function loadHighlighter() {
  const esc = script.match(/^const esc = .*$/m)[0];
  const fn = script.match(/function highlightToml\(src\) \{[\s\S]*?\n\}/)[0];
  return new Function(`${esc}\n${fn}\nreturn highlightToml;`)();
}

const SAMPLE = [
  '# Generated by android-kickstart on 2026-08-21T16:28:39.955Z',
  '',
  '[versions]',
  'agp = "9.2.1"',
  'composeCompiler = "2.4.10" # == kotlin',
  '',
  '[libraries]',
  'androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }',
  '',
  '[plugins]',
  'hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }',
].join('\n');

test('highlighter never leaks its own markup as visible text', () => {
  const out = loadHighlighter()(SAMPLE);
  // The exact corruption that shipped: the string rule matched the quotes inside
  // class="cmt" and wrapped them, so `"cmt">` appeared on screen as literal text.
  assert.ok(!out.includes('<span class=<span'), 'a span attribute was itself highlighted');
  assert.ok(!/class=<span/.test(out), 'class attribute corrupted');
  for (const cls of ['cmt', 'sec', 'key', 'str']) {
    assert.ok(out.includes(`class="${cls}"`), `missing ${cls} spans`);
  }
});

test('highlighter renders to the original text once tags are stripped', () => {
  const out = loadHighlighter()(SAMPLE);
  const rendered = out
    .replace(/<\/?span[^>]*>/g, '')
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>');
  assert.equal(rendered, SAMPLE, 'highlighting altered the visible text');
});

test('each construct gets the right class', () => {
  const out = loadHighlighter()(SAMPLE);
  assert.match(out, /<span class="sec">\[versions\]<\/span>/);
  assert.match(out, /<span class="key">agp<\/span>/);
  assert.match(out, /<span class="str">&quot;9\.2\.1&quot;<\/span>/);
  assert.match(out, /<span class="cmt"># Generated by/);
  assert.match(out, /<span class="cmt"> # == kotlin<\/span>/);
});

test('libraries.json covers every selectable option', () => {
  const libs = JSON.parse(readFileSync(join(toolRoot, 'libraries.json'), 'utf8'));
  for (const key of ['hilt', 'koin', 'retrofit', 'ktor', 'room', 'datastore', 'none']) {
    assert.ok(libs[key], `missing metadata for "${key}"`);
    assert.ok(libs[key].summary, `${key} has no summary`);
    assert.ok(libs[key].logo, `${key} has no logo`);
  }
});

// The presets hard-code choice values; if an option is ever renamed in GROUPS these would
// silently configure nothing.
// Index-based rather than a built RegExp: escaping \s through a JS string into new RegExp
// silently degrades it to a literal 's'.
function extractConst(name) {
  const head = 'const ' + name + ' = {';
  const from = script.indexOf(head);
  assert.ok(from !== -1, name + ' not found in the page script');
  const to = script.indexOf('\n};', from);
  assert.ok(to !== -1, name + ' has no closing brace');
  const src = script.slice(from, to + 3);
  return new Function(src + '; return ' + name + ';')();
}

test('every preset selects real options', () => {
  const groups = extractConst('GROUPS');
  const presets = extractConst('PRESETS');

  for (const [name, preset] of Object.entries(presets)) {
    for (const [group, value] of Object.entries(preset.choices)) {
      assert.ok(groups[group], `preset "${name}" sets unknown group "${group}"`);
      const valid = groups[group].opts.map(([v]) => v);
      assert.ok(valid.includes(value), `preset "${name}" sets ${group}=${value}, not one of ${valid.join('/')}`);
    }
    // Every group must be covered, or clicking a preset leaves a stale choice behind.
    for (const group of Object.keys(groups)) {
      assert.ok(group in preset.choices, `preset "${name}" does not set "${group}"`);
    }
  }
});
